## Output the constraints on DA/rd and H(z)rd from spec-z, photo-z, spec-z+cross, spec-z+photo-z+cross in a table. 
Update the result with Sigma_fog/(1+z). --03-28-2023

In [1]:
import os, sys
import numpy as np
from pathlib import Path
sys.path.append("/home/zjding/csst_bao/fisher_pkmu/")
from mcmc_funs import growth_factor
from astropy.table import Table

In [2]:
speed_c = 299792.458    # speed of light, km/s
Omega_m = 0.3075

survey_area = 17500.0
kmax = 0.3
zmin = 0.
zmax = 1.6
nzbins = 8
zbins = np.linspace(zmin, zmax, nzbins+1)

const_low = 0.99
const_up = 1.01

kwidth = 0.005

Pspecz_sys = "1.0"

skyarea_total = 4*np.pi * (180./np.pi)**2.0
fsky = survey_area/skyarea_total
G_0 = growth_factor(0.0, Omega_m)       # G_0 at z=0, normalization factor 

# ## estimate the power spectrum damping parameter $\Sigma_{specz}$, $\Sigma_{pz}$ from the spec-z and photo-z uncertainty
sigma_specz = 0.002
sigma_photoz = 0.025     # does not matter here if we only care about the spec-z result
Sigma_fog = 7.0          # Finger-of-God damping term

tracer_list = ['specz', 'photoz', 'specz_add_cross', 'specz_photoz_add_cross']
if Sigma_fog > 0.0:
    params_str_list = ['11110101010101', '11101010101010', '11111111111111', '11111111111111']

#idir0 = "/home/zjding/csst_bao/fisher_pkmu/BAO_part/Fisher_sigma_alphas/numerical_method/secondgen/output/"
#alpha_dir0 = f"{idir0}/sigma_alpha/vary_params_{const_low}_{const_up}/Sigma_fog_{Sigma_fog:.1f}/%s/k_width{kwidth}/Pspecz_sys{Pspecz_sys}/params_bf1.0/"

idir0 = "/home/zjding/csst_bao/fisher_pkmu/BAO_part/Fisher_sigma_alphas/numerical_method/default/output/"
alpha_dir0 = f"{idir0}/sigma_alpha/vary_params_{const_low}_{const_up}/Sigma_fog_{Sigma_fog:.1f}/%s/k_width{kwidth}/Pspecz_sys{Pspecz_sys}/params_bf1.0/"   # for Psys=0
recon_dir_list = ['pre_recon', 'post_recon']

## collect data

In [3]:
def read_data(alpha_dir, params_str, sigma_alperp_list, sigma_alpara_list):
    filename = f"sigma_alpha_{tracer}_tracer_zerror_specz{sigma_specz:.3f}_photoz{sigma_photoz:.3f}_kmax{kmax:.2f}_params{params_str}.npz"

    ifile = Path(alpha_dir, filename)
    data = np.load(ifile)
    sigma_alphas_mar = data['alphas_mar']

    sigma_alperp_list.append(sigma_alphas_mar[:, 2] * 100)  # transfer to per cent
    sigma_alpara_list.append(sigma_alphas_mar[:, 3] * 100)
    return sigma_alperp_list, sigma_alpara_list

In [4]:
sigma_alperp_list = []
sigma_alpara_list = []

for tracer, params_str in zip(tracer_list, params_str_list):
    if tracer == 'photoz':
        recon_dir = recon_dir_list[0]
        ##alpha_dir = alpha_dir0.format(idir0, const_low, const_up, zmin, zmax, nzbins, Sigma_fog, recon_dir, kwidth, Pspecz_sys)
        alpha_dir = alpha_dir0%(recon_dir)
        sigma_alperp_list, sigma_alpara_list = read_data(alpha_dir, params_str, sigma_alperp_list, sigma_alpara_list)
    else:
        for recon_dir in recon_dir_list:
            alpha_dir = alpha_dir0%(recon_dir)
            sigma_alperp_list, sigma_alpara_list = read_data(alpha_dir, params_str, sigma_alperp_list, sigma_alpara_list)
        
sigma_alperp_array = np.array(sigma_alperp_list).T    # transpose it to make the row as the redshift index
sigma_alpara_array = np.array(sigma_alpara_list).T

In [5]:
sigma_alphas_array = np.hstack((sigma_alperp_array, sigma_alpara_array))
print(sigma_alphas_array.shape)

(8, 14)


In [6]:
data = [zbins[0:-1], zbins[1:]] + sigma_alperp_list + sigma_alpara_list
data

[array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4]),
 array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6]),
 array([ 4.74066766,  1.74130739,  1.12031334,  0.84110686,  0.77040378,
         1.4121305 ,  5.04690568, 24.51901026]),
 array([ 2.25977766,  0.90957142,  0.6539332 ,  0.53060696,  0.53094793,
         1.12112372,  4.58883556, 24.51901026]),
 array([6.57809909, 2.5466111 , 1.6355923 , 1.2178468 , 1.00168856,
        0.89837463, 0.86578434, 0.82619238]),
 array([4.7147418 , 1.72429954, 1.08433883, 0.80396137, 0.70100081,
        0.93140478, 1.78146575, 3.92486628]),
 array([1.32293079, 0.72178706, 0.6381136 , 0.52923005, 0.52093464,
        0.80933632, 1.69251593, 3.92486628]),
 array([4.71454716, 1.72405683, 1.08264196, 0.80150294, 0.69207226,
        0.76766783, 0.81008408, 0.80865188]),
 array([0.91530916, 0.65649117, 0.63724327, 0.52920851, 0.52066841,
        0.7147838 , 0.80583728, 0.80865188]),
 array([12.20566884,  4.64538284,  3.00514817,  2.23828116,  1.98527603,
         3.14

In [7]:
len(data)

16

In [8]:
name_list = ['zmin', 'zmax', 'alperp_specz_pre', 'alperp_specz_post', 'alperp_photoz', 'alperp_specz_pre+cross', 'alperp_specz_post+cross', 'alperp_joint_pre', 'alperp_join_post', \
                             'alpara_specz_pre', 'alpara_specz_post', 'alpara_photoz', 'alpara_specz_pre+cross', 'alpara_specz_post+cross', 'alpara_joint_pre', 'alpara_join_post']
print(len(name_list))
res = Table(data, names=name_list)
res

16


<Table length=8>
       zmin               zmax        ...  alpara_joint_pre   alpara_join_post 
     float64            float64       ...      float64            float64      
------------------ ------------------ ... ------------------ ------------------
               0.0                0.2 ...  12.19516846470568  4.492756677940939
               0.2                0.4 ...  4.638286669434908 1.9174789298372887
               0.4 0.6000000000000001 ... 2.9900094573096263 1.4788072003162482
0.6000000000000001                0.8 ... 2.2226041199488864 1.1992020020066476
               0.8                1.0 ... 1.9563905007816356 1.1877193599430318
               1.0 1.2000000000000002 ...  2.969339161075215 2.1916538112075115
1.2000000000000002 1.4000000000000001 ...  8.372029587045004  7.454695860297539
1.4000000000000001                1.6 ... 22.875511910817796 22.875511910817796

In [9]:
ncol_alphas = sigma_alphas_array.shape[1]//2

In [10]:
odir = "./Table/"
if not os.path.exists(odir):
    os.makedirs(odir)

In [11]:
header=" "
for i in name_list:
    header += i + ", "

ofile = odir + "sigma_DA_Hz_Sigmafog_{0:.1f}_Pspeczsys{1}_pre_postrecon.csv".format(Sigma_fog, Pspecz_sys)

with open(ofile, 'w') as fwriter:
    for i in range(nzbins):
        zmin, zmax = zbins[i], zbins[i+1]
        text = f"{zmin:.1f} < z < {zmax:.1f}"
        for j in range(2):
            text += f"& {sigma_alphas_array[i, 0+j*ncol_alphas]:.2f} ({sigma_alphas_array[i, 1+j*ncol_alphas]:.2f}) "
            text += f"& {sigma_alphas_array[i, 2+j*ncol_alphas]:.2f} " 
            text += f"& {sigma_alphas_array[i, 3+j*ncol_alphas]:.2f} ({sigma_alphas_array[i, 4+j*ncol_alphas]:.2f}) "
            text += f"& {sigma_alphas_array[i, 5+j*ncol_alphas]:.2f} ({sigma_alphas_array[i, 6+j*ncol_alphas]:.2f}) "
            if j == 0:
                text += "& "
        
        text += " \\\\\n"
        fwriter.write(text)

## only for pre-recon results

In [12]:
name_list_pre = ['zmin', 'zmax', 'alperp_specz_pre', 'alperp_photoz', 'alperp_specz_pre+cross', 'alperp_joint_pre', \
                             'alpara_specz_pre', 'alpara_photoz', 'alpara_specz_pre+cross', 'alpara_joint_pre']

ofile = odir + "sigma_DA_Hz_Sigmafog_{0:.1f}_Pspeczsys{1}_pre_recon.csv".format(Sigma_fog, Pspecz_sys)

header=" "
for i in name_list_pre:
    header += i + ", "

with open(ofile, 'w') as fwriter:
    for i in range(nzbins):
        zmin, zmax = zbins[i], zbins[i+1]
        text = f"{zmin:.1f} < z < {zmax:.1f}"
        for j in range(2):
            text += f"& {sigma_alphas_array[i, 0+j*ncol_alphas]:.2f} "
            text += f"& {sigma_alphas_array[i, 2+j*ncol_alphas]:.2f} " 
            text += f"& {sigma_alphas_array[i, 3+j*ncol_alphas]:.2f} "
            text += f"& {sigma_alphas_array[i, 5+j*ncol_alphas]:.2f} "
            if j == 0:
                text += "& "
        
        text += " \\\\\n"
        fwriter.write(text)